
sudo: require
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash >  /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl 
  - gcloud auth activate-service-account --key-file service-account.json


# deployment process
# - create github repo
# - add deployment scripts to repo
# - Tie repo to travis ci
# - create google kubernetes cluster
# - install gcloud sdk cli
# - configure the sdk with gcloud auth info
# - create service account with key on gcloud (IAM)
# - put account key into work folder
# - install docker image with ruby installed, run travis-cli  
#    -- docker run -it -v %cd%:/app ruby:2.4 sh
#    -- gem install travis
#    -- travis login (travis login --github-token YOUR_PERSONAL_TOKEN --com)
#    -- encrypt the service account key (travis encrypt-file service-account.json -r amoat7/multi-container --com)
#    -- add openssl file to .travis.yml file 
#    -- remove service-account.json file 
#    -- 

# - login to docker cli
# - 'run test'
# - if tests are successful, run a script to deploy newest images
# - build all our images, tag each one, push to docker hub
# - apply all configs in the k8s folder
# - imperatively set latest images on each deployment 
